project:
  type: website
  output-dir: docs

website:
  title: "Abeba N. Turi"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Publications"
        href: publications.qmd

format:
  html:
    toc: true
    theme: cosmos
    css: styles.css
